local x1="a"
local x2="i"
local x3="u"
local x4="e"
local x5="o"
local x6="h"
local y1="y"
local y2="и"
local y3="о"
local y4="е"
local y5="я"
return {
["dumb"..x1.."s".."s".."es"] = "idiots",
["dumb"..x1.."s".."s"] = "idiot",
[" "..x1.."s".."s".."hole"] = " b"..x3.."t".."t".."hole",
[" "..x1.."s".."s"] = " face",
["the f"..x3.."c".."k"] = "the heck",
["you f"..x3.."c".."k"..x2.."ng"] = "you really",
["he f"..x3.."c".."k"..x2.."ng"] = "he really",
["she f"..x3.."c".."k"..x2.."ng"] = "she really",
["they f"..x3.."c".."k"..x2.."ng"] = "they really",
["it f"..x3.."c".."k"..x2.."ng"] = "it really",
["i f"..x3.."c".."k"..x2.."ng"] = "i really",
["f"..x3.."c".."k"..x2.."ng"] = "freaking",
["f"..x3.."c".."k"] = "frick",
["giv(.+) a sh"..x2.."t"] = function(e) return "car"..e end,
["sh"..x2.."tt"] = "p"..x5..x5.."p",
["sh"..x2.."t"] = "crap",
["p"..x2.."s".."s"] = "p"..x4..x4,
["son of a ".."b"..x2.."tch"..x4] = "son of a mother",
["b"..x2.."t".."ch"] = "b"..x3.."t".."t",
["dô uma ".."m"..x4.."rd"..x1] = "me importo",
["dá uma ".."m"..x4.."rd"..x1] = "se importa",
["damos uma ".."m"..x4.."rd"..x1] = "nos importamos",
["dão uma ".."m"..x4.."rd"..x1] = "se importam",
["dei uma ".."m"..x4.."rd"..x1] = "me importei",
["deu uma ".."m"..x4.."rd"..x1] = "se importou",
["daram uma ".."m"..x4.."rd"..x1] = "se importaram",
["m"..x4.."rd"..x1.." dessa"] = "porcaria dessa",
["m"..x4.."rd"..x1.." desse"] = "porcaria desse",
["m"..x4.."rd"..x1.." disso"] = "porcaria disso",
["que ".."m"..x4.."rd"..x1.." de"] = "que porcaria de",
["que ".."m"..x4.."rd"..x1] = "que diacho",
["é uma ".."m"..x4.."rd"..x1] = "é um diacho",
["m"..x4.."rd"..x1.."".." de"] = "c"..x5.."cô de",
["p"..x3.."t"..x1.." ".."m"..x4.."rd"..x1] = "porcaria",
["m"..x4.."rd"..x1] = "meleca",
["que ".."b"..x5.."st"..x1] = "que porcaria",
["é uma ".."b"..x5.."st"..x1] = "é um diacho",
["b"..x5.."st"..x1] = "c"..x5.."cô",
["filha da ".."p"..x3.."t"..x1] = "filha da mãe",
["(%A)c"..x3.."(%A)"] = function(start,endi) return start.."nariz"..endi end,
["b"..x3.."md"..x1] = "b"..x3.."mb"..x3.."m",
["vai ".."c"..x1.."g"..x1.."r"] = "vai ", -- Unfinished due to our difficulty.
["c"..x1.."g"..x3.."ei"] = "fiz c"..x5.."cô",
["c"..x1.."g"..x5.."u"] = "fez c"..x5.."cô",
["c"..x1.."g"..x5] = "faço c"..x5.."cô",
["c"..x1.."g"..x1.."ndo"] = "fazendo c"..x5.."cô",
["c"..x1.."g"..x1.."r"] = "fazer c"..x5.."cô",
["c"..x1.."g"..x1] = "faz c"..x5.."cô",
}
